#!/bin/bash --
# Shell Script to Query the Wikipedia.
# It can be used to output the query to the console, but can also 
# just open the wikipedia page in any browser.

VERSION=0.03

function display_help(){
cat << EOF |less
NAME
    This script uses elinks (by default) to query wikipedia.org for 
    a specified keyword.
    The output will be printed to standard out.
    
SYNOPSIS
    `basename $0` [-hnsuv -i patt -c patt -b prog -l lang] Query
    `basename $0` -o [-l lang] Query
    `basename $0` [-h] 
    `basename $0` -v 
   
    -n	do not colorize	
    -o	open wikipedia page in browser	    -s	display only summary
    -u	Just output the Query-URL	    -v	display version
    -C	simple colorization		    -h	display help		   

    -i patt	colorize pattern (case insensitive)
    -c patt	colorize pattern (case-sensitive)
    -b prog	use prog as browser (by default: elinks)
    -l lang	use Language (currently, only de and en are supported)

    Query can be any Term to search for at wikipedia. Special characters 
    will be taken care of. Note that only 1 Query Term is supported,
    however this term can consist of one or more words.
    Configuration can also be controlld by creating a runcontrol file
    .wikirc in your home directory.
    Note, that when requesting to open the article in a browser, other 
    parameters will be ignored. The same holds for -h and -v.
EOF
}

function getVersion(){
cat <<EOF
    "$(basename "${0}")" Version: "${VERSION}"
EOF
}


function errorExit(){
    echo "$*" >&2
    exit 3
}

function colorize(){
if [ "${IGNCASE}" = "true" ]; then
    OUTPUT=$(echo -e "`cat`"|sed -s "s|\(${PATT}\)|\\\033\[0;31m\1\\\033\[0m|gi")
else
    OUTPUT=$(echo -e "`cat`"|sed -s "s|\(${PATT}\)|\\\033\[0;31m\1\\\033\[0m|g")
fi
echo -e "${OUTPUT}"
}

function stripOutput(){
if [ "${LOCAL}" = "de" ]; then 
    MARKER="Einordnung"
    MARKER2="Bearbeiten"
elif [ "${LOCAL}" = "en" ]; then
    MARKER="Categories"
    MARKER2="edit"
fi

# Now comes the magic: Strip everything from Marker to end,
# cause this is only the linkdump
echo "`cat`"| sed  -e "/${MARKER}/,$ D" -e "s|\[[0-9]*\]||g" -e "s|\[IMG\]||g" -e "s|\[${MARKER2}\]||g"
}

function openurl(){
    "${BROWSER}" "${URL}"
}

function summary(){
    if [ "${COLOR}" = "true" ]; then
	"${BROWSER}" -dump "${URL}" |grep -v copyright | head -n 22 \
	| tail -n 17  |stripOutput | colorize
    else
	"${BROWSER}" -dump "${URL}" |grep -v copyright | head -n 22 \
	| tail -n 17  | stripOutput
    fi
}

function getInfo(){
    LINES=$("${BROWSER}" -dump "${URL}" |wc -l)
    LINES=$(expr ${LINES} - 6)
    if [ "${COLOR}" = "false" ]; then
	"${BROWSER}" -dump "${URL}"| tail -n ${LINES}  |stripOutput  
    else
	"${BROWSER}" -dump "${URL}"| tail -n ${LINES}  |stripOutput |colorize 
    fi
}

# First read in the Run configuration File, if one is found 
if [ -r ~/.wikirc ]; then
    source ~/.wikirc
fi

# Process commandline parameters
while getopts "Cvuhosnl:b:c:i:" ARGS 
    do
	case ${ARGS} in
	i) IGNCASE="true";COLOR="true"; PATT=${OPTARG};;
	o) USEBROWSER="true" ;;
	s) SHORT="true" ;;
	n) COLOR="false" ;;
	u) OUTPUTURL="true" ;;
	C) COLOR="true" ;;
	c) IGNCASE="false";COLOR="true"; PATT=${OPTARG}  ;;
	b) ABROWSER=${OPTARG} ;;
	l) LOCAL=${OPTARG} ;;
	v) getVersion; exit 0 ;;
	h) display_help; exit 0 ;;
	*) display_help; exit 1 ;;
	esac
done

shift `expr ${OPTIND} - 1`


# Setting Up some Variables, to determine, what actually to do
#if [ -z "$1" ]; then
#    display_help
#    exit 1;
#fi

if [ -z "${IGNCASE}" ]; then
    IGNCASE="false"
fi

if [ -z "${COLOR}" ]; then
    COLOR="false"
elif [ "${COLOR}" != "false" ]; then 
    COLOR="true"
    if [ -z "${PATT}" ]; then
    PATT="$*"
    fi
fi

# Per default we use the german localized version of 
# Wikipedia
if [ -z "${LOCAL}" ]; then
    LOCAL="de"
fi

# Check for Alternative Browser
if [ -n "${ABROWSER}" ]; then
    BROWSER=$(which "${ABROWSER}") ||  errorExit "${ABROWSER} nicht gefunden"  
else
   { BROWSER=$(which elinks) || BROWSER=$(which lynx) ; } || errorExit "kein Browser gefunden"
fi


# Open page in Browser?
if [ -z "${USEBROWSER}" ]; then
    USEBROWSER="false"
fi

# Output only a summary?
if [ -z  "${SHORT}" ]; then
    SHORT="false"
fi

# Output only the URL?
if [ -z  "${OUTPUTURL}" ]; then
    OUTPUTURL="false"
fi

# Now translate the input into something, we can use for the Wikipedia
ARGUMENT="$(echo "$*" |sed -e 's|ü|%C3%BC|g' -e 's|ä|%C3%A4|g' -e 's|ö|%C3%B6|g' -e 's|[[:space:]]|_|g' -e 's|\"||g' -e 's|ß|%C3%9F|g')"
LOCAL="$(echo "${LOCAL}"|tr [:upper:] [:upper:])"
URL="http://${LOCAL}.wikipedia.org/wiki/${ARGUMENT}"

#errorExit "Broser: $BROWSER Local: $LOCAL COLOR: $COLOR IGNCASE: $IGNCASE"


# Depending on some Variables, we do some different things here
if [ "${USEBROWSER}" = "true" ]; then
    openurl 
    exit 0;
fi

if [ "${SHORT}" = "true" ]; then
    summary  
    exit 0;
fi

if [ "${OUTPUTURL}" = "true" ]; then
    if [ "${COLOR}" = "false" ]; then
	echo "${URL}" 
    else
	echo -e "\033[0;34m${URL}\033[0m" 
    fi
    exit 0;
fi

getInfo
